name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and analyze
        env:
          GITHUB_TOKEN: >-
            341873e9-9338-4ff8-a71b-227a49a46f69-f50da72a-4107-41f2-a0c8-acbae33c103d
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=iamneo-production_341873e9-9338-4ff8-a71b-227a49a46f69-f50da72a-4107-41f2-a0c8-acbae33c103d
          -Dsonar.login=811c9a490983734401ba4e491eaefc8bfa7281de
      - name: Trigger API
        if: always()
        env:
          API_URL: '${{ secrets.API_URL }}'
          API_SECRET: '${{ secrets.API_SECRET }}'
        run: >
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          GITHUB_USERNAME=$GITHUB_ACTOR

          API_PAYLOAD="{ \"repo_id\": \"$REPO_NAME\", \"branch_name\":
          \"$BRANCH_NAME\", \"github_username\": \"$GITHUB_USERNAME\",
          \"api_secret\": \"$API_SECRET\" }"

          curl -X POST -H "Content-Type: application/json" -d "$API_PAYLOAD"
          $API_URL
